name: Weekend-Chat-CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  client_ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js for client
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Install dependencies
      run: npm ci

    - name: prettier formatting
      run: npm run prettier:fix
    
    - name: linting
      run: npm run lint

  server_ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js for server
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    
    - name: Install dependencies
      run: npm ci

    - name: prettier formatting
      run: npm run prettier:fix